# frozen_string_literal: true
source 'https://rubygems.org'
gem 'rspec'
gem 'sinatra'
#gem 'redis', '~>3.2'
#gem 'hiredis' #, '~> 0.4.5'
gem "hiredis", "~> 0.6.0"
gem "redis", ">= 3.2.0"
gem 'mongo'
gem 'chunky_png'
gem 'yard'
# gem 'rails'